#!/usr/bin/env ruby

require_relative "config/boot"
require_relative "config/environment"


chars=Char.all
records=chars.count

pb = ProgressBar.create(:title => "Importing WalletJournals", :starting_at => 0, :total => records, :format => '%a |%b>>%i| %p%% %t', length: 100 )

chars.each do |char|
  char.wallet_import(3000)
  pb.increment
end