#!/usr/bin/env ruby
require_relative "config/boot"
require_relative "config/environment"

session = Moped::Session.new([ "127.0.0.1:27017", "127.0.0.1:27018", "127.0.0.1:27019" ])
session.use :evescore_development

bounties = session[:bounties]
incursions = session[:incursions]

records = bounties.find.count

pb = ProgressBar.create(:title => "Migrating Bounty", :starting_at => 0, :total => records, :format => '%a |%b>>%i| %p%% %t', length: 100 )

bounties.find.each do |bounty|
  w=WalletRecord.new(ts: bounty["ts"], char_id: bounty["char_id"], corp_id: bounty["corp_id"], amount: bounty["bounty"], tax: bounty["tax"], ref_type_id: 85)
  w.save
  bounty["kills"].each do |kill|
    w.kills.new(ts: bounty["ts"], char_id: bounty["char_id"], corp_id: bounty["corp_id"], rat_id: kill["rat_id"], rat_amount: kill["rat_amount"])
    w.save
  end
  pb.increment
end

pb = ProgressBar.create(:title => "Migrating Bounty", :starting_at => 0, :total => records, :format => '%a |%b>>%i| %p%% %t', length: 100 )

incursions.find.each do |incursion|
  w=WalletRecord.new(ts: incursion["ts"], char_id: incursion["char_id"], corp_id: incursion["corp_id"], amount: incursion["reward"], tax: 0, ref_type_id: 99)
  w.save
  pb.increment
end

